// Generated by CoffeeScript 1.12.5
(function() {
  var app, gameServer, io, port, server, verbose;

  app = require('express')();

  server = require('http').Server(app);

  io = require('socket.io')(server);

  port = process.env.PORT || 5000;

  verbose = true;

  server.listen(port, function() {
    return console.log("server started at port: %s", port);
  });

  app.get('/', function(req, res) {
    return res.sendFile(__dirname + '/index.html');
  });

  app.get('/*', function(req, res, next) {
    var file;
    file = req.params[0];
    if (verbose) {
      console.log('\t :: Express :: file requested : ' + file);
    }
    return res.sendfile(__dirname + '/' + file);
  });

  gameServer = require('./game.server.js')();

  io.on('connection', (function(_this) {
    return function(client) {
      client.userid = UUID();
      client.emit('onconnected', {
        id: client.userid
      });
      gameServer.findGame(client);
      console.log('\t socket.io:: player ' + client.userid + ' connected');
      client.on('message', function(m) {
        return gameServer.onMessage(client, m);
      });
      return client.on('disconnect', function() {
        return console.log('\t socket.io:: client disconnected ' + client.userid + ' ' + client.game_id);
      });
    };
  })(this));

}).call(this);

//# sourceMappingURL=app.js.map
