// Generated by CoffeeScript 1.12.5
(function() {
  var game;

  game = {};

  window.onload = (function(_this) {
    return function() {
      game = new GameCore();
      return game.start();
    };
  })(this);

}).call(this);

//# sourceMappingURL=game.client.js.map
