// Generated by CoffeeScript 1.12.5
(function() {
  var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  module.exports = (function(superClass) {
    extend(_Class, superClass);

    function _Class() {
      this.update = bind(this.update, this);
      this.name = "Test";
    }

    _Class.prototype.update = function() {
      this.gameObject.mesh.rotation.y += 1;
      return this.gameObject.mesh.__dirtyRotation = true;
    };

    return _Class;

  })(require('../Component'));

}).call(this);

//# sourceMappingURL=Test.js.map
