// Generated by CoffeeScript 1.12.5
(function() {
  var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    slice = [].slice;

  module.exports = (function() {
    function _Class() {
      this.receive = bind(this.receive, this);
      this.gameObject = null;
      this.name = "component";
    }

    _Class.prototype.receive = function() {
      var args;
      args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
    };

    return _Class;

  })();

}).call(this);

//# sourceMappingURL=Component.js.map
