// Generated by CoffeeScript 1.12.5
(function() {
  var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    slice = [].slice;

  module.exports = (function() {
    function _Class(mesh) {
      this.mesh = mesh;
      this.broadcast = bind(this.broadcast, this);
      this.removeComponent = bind(this.removeComponent, this);
      this.getComponent = bind(this.getComponent, this);
      this.addComponent = bind(this.addComponent, this);
      this.components = {};
    }

    _Class.prototype.addComponent = function(comp) {
      comp.gameObject = this;
      return this.components[comp.name] = comp;
    };

    _Class.prototype.getComponent = function(name) {
      return this.components[name];
    };

    _Class.prototype.removeComponent = function(name) {
      return this.components[name] = null;
    };

    _Class.prototype.broadcast = function() {
      var args, comp, name, ref, results;
      args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
      ref = this.components;
      results = [];
      for (name in ref) {
        comp = ref[name];
        results.push(comp.receive.apply(comp, args));
      }
      return results;
    };

    return _Class;

  })();

}).call(this);

//# sourceMappingURL=GameObject.js.map
