// Generated by CoffeeScript 1.12.5
(function() {
  var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  module.exports = (function() {
    function _Class(initializer) {
      this.update = bind(this.update, this);
      this.addLight = bind(this.addLight, this);
      this.addObject = bind(this.addObject, this);
      this.pscene = new Physijs.Scene();
      this.camera = new THREE.PerspectiveCamera(75, window.innerWidth / window.innerHeight, 0.1, 10000);
      this.camera.position.set(0, -0.5, 1);
      this.objects = [];
      initializer(this);
    }

    _Class.prototype.addObject = function(object) {
      this.objects.push(object);
      return this.pscene.add(object.mesh);
    };

    _Class.prototype.addLight = function(light) {
      return this.pscene.add(light);
    };

    _Class.prototype.update = function() {
      var comp, i, len, name, object, ref, ref1;
      ref = this.objects;
      for (i = 0, len = ref.length; i < len; i++) {
        object = ref[i];
        ref1 = object.components;
        for (name in ref1) {
          comp = ref1[name];
          if (typeof comp.update === "function") {
            comp.update();
          }
        }
      }
      return this.pscene.simulate();
    };

    return _Class;

  })();

}).call(this);

//# sourceMappingURL=Scene.js.map
